### ISSUE TITLE
As a logged in user, I want to go to the “Groups” page so I can access its features.

### ISSUE THREAD

**Issue by willson8878** [prafulrpatel389/F7204_HEADS-UP#10]

**Comment by matthewcuevas** [comment]
## Story/Task Details

- [x] Design the "Groups" page 
- [x] Code the "Groups" page
- [x] Design the "Groups" button on the navigation bar
- [x] Design the "Groups" option on the hamburger menu



## Acceptance Scenarios
**Scenario: A user wants to access “Groups” pages from top navigation bar.**

- 	GIVEN the user is on any pages of application and press top navigation button;
- 	WHEN the user presses “Groups” button location on top navigation bar.
- THEN the user transfer to “Groups” page.

**Scenario: A user wants to access “Groups” pages from bottom navigation bar.**

- 	GIVEN the user is on any pages of application and press bottom navigation button;
- 	WHEN the user presses “Groups” button location on bottom navigation bar.
- THEN the user transfer to “Groups” page.
