### ISSUE TITLE
As a logged in user, I want to go to the “Activities” page so I can access its features.

### ISSUE THREAD

**Issue by willson8878** [prafulrpatel389/F7204_HEADS-UP#7]

**Comment by matthewcuevas** [comment]
## Story/Task Details

- [x] Design and Code the "Login" page
- [x] Design and Code the "Login" button
- [x] Design and Code the "Register" button
- [x] Design and Code the "Login" page
- [x] Create DB Table for User Profiles
- [ ] Write Login Controller
- [ ] Write Back-End Logic



## Acceptance Scenarios
**Scenario: A user wants to access “Activities” pages from top navigation bar.
	GIVEN the user is on any pages of application and press top navigation button;
	WHEN the user presses “Activities” button location on top navigation bar.
THEN the user transfer to “Activities” page.

**Scenario: A user wants to access “Activities” pages from bottom navigation bar.
	GIVEN the user is on any pages of application and press bottom navigation button;
	WHEN the user presses “Activities” button location on bottom navigation bar.
THEN the user transfer to “Activities” page.
