### ISSUE TITLE
As a logged in user, I want to go to the “Articles” page so I can access its features.

### ISSUE THREAD

**Issue by willson8878** [prafulrpatel389/F7204_HEADS-UP#9]

**Comment by matthewcuevas** [comment]
## Story/Task Details

- [x] Design the "Articles" page 
- [x] Code the "Articles" page
- [x] Design the "Articles" button on the navigation bar
- [x] Design the "Articles" option on the hamburger menu



## Acceptance Scenarios
**Scenario: A user wants to access “Articles” pages from top navigation bar.**

- 	GIVEN the user is on any pages of application and press top navigation button;
- 	WHEN the user presses “Articles” button location on top navigation bar.
- THEN the user transfer to “Articles” page.

**Scenario: A user wants to access “Articles” pages from bottom navigation bar.**

- 	GIVEN the user is on any pages of application and press bottom navigation button;
- 	WHEN the user presses “Articles” button location on bottom navigation bar.
- THEN the user transfer to “Articles” page.
